import { Component, Input, OnInit } from '@angular/core';


@Component({
  selector: 'fifak-geneteka-opis',
  templateUrl: './geneteka-opis.component.html',
  styleUrls: ['../box-size-scroll.scss','./geneteka-opis.component.scss']
})
export class GenetekaOpisComponent implements OnInit {
  @Input() idn = 0;  
  @Input() txt = '';
  p_1_a = 'Geneteka, to prężnie przyrastająca baza zindeksowanych akt: wyznaniowych ksiąg metrykalnych i stanu cywilnego, producentem Geneteki sensu largo jest rzesza wolontariuszy indeksujący wybrane przez siebie księgi metrykalne, jak i wybrane informacje. Cechami wspólnymi dla wszystkich rekordów są: rok w którym akt powstał, parafia/urząd sporządzająca akt, miejscowość, w przypadku aktu: narodzin/chrztu/zgonu, zazwyczaj uzyskujemy imiona dziecka, nazwisko i imiona ojca oraz matki; (czasami w uwagach uzyskujemy pełną datę urodzenia oraz chrztu, adres, przy zmarłych wiek osoby, rzadko kiedy poznajemy dziadków dziecka lub inne koligacje; natomiast w przypadku aktu małżeństwa zazwyczaj jest pan młody i panna młoda z imienia i nazwiska, czasami też dokładna data i adres, oraz wiek podczas zawarcia małżeństwa,czy informacja o tym czy byli wdowcami, jak i informacje o rodzicach małżonków. Jak zapewne państwo wiedzą,zdecydowana większość aktów posiada jeszcze inne ważne informacje o osobach jak chociażby statut i/lub zawód osób, i różne inne..';
  p_1_b = 'Obecność Geneteki w sieci, wraz z darmowym doń dostępem z dowolnego miejsca na świecie oraz nierzadkie podlinkowanie skanów konkretnych,do poszczególnych rekordów, jest nieocenioną pomocą genealogiczną, w niektórych przypadkach niesamowicie przyspieszającą wstępną kewrendendę genealogiczną, choć ostatnich czasy (rok 2022) niemalże każdego dnia przybywa średnio 8 indeksów dotyczących różnych miejscowości jaki różnych okresów roczników i wyznań, należy pamiętać iż brak szukanego rekordu z jakiegokolwiek miejsca,nawet w przypadku gdy są indexy z danego rocznika, nie determinuje tego że dane wydarzenie miejsca nie miało, bowiem w niektórych parafiach tworzonych było równolegle kilka ksiąg dla różnych części/przysiółków/itp, również na uwadze mieć trzeba czy dana księga to unikat, czy duplikat, sporo ksiąg która dotrwała do dzisiejszych czasów są to kopie, poprzednich kopii a trzeba pamiętać iż ksero to wynalazek z II połowy XX wieku (!! prosze nie kserować starodróków światło ostre je niszczy), księgi były przepisywane i nierzadko skutkowało to powstaniem różnych nieścisłości jak i poważniejszych błędów. Geneteka jest tylko jedną spośród wielu tego typu baz, pozwolę sobie wymienić inne przykłady takie jak baza LubGens, baza Pomorskiego TG, “Poznań Project”, czy “Basia” (WTG Gniazdo);';
  p_1_c = 'Przyjęta przez PTG metodologia sprawia iż w bazie błędów bez liku jest, treść nadesłanego przez wolontariusza indeksu jest zamieszczana bez jakiegokolwiek sprawdzenia (moim skromnym zdaniem indeksy tworzone winny być w trójkach, lub co najmniej parach - pierwszy/a wykonuje najcięższą robotę, drugi/a sprawdza zgodność indeksu z źródłem, ewentualnie trzeci/a dokonuje drugiego sprawdzenia - wówczas błędów byłoby jak na lekarstwo). Spośród grubych błędów na szczęście nieczęstych są różnorakie roszady wpisanie do złej rubryki przeczytanej treści - w przeglądaniu całej parafii wyszukując różnych fragmentarycznych danych jak chociażby np rodziców po imionach zamiast nazwisk, lub po innym kluczu można niekiedy wyłapać takie błędnie zindeksowane rekordy, niestety zasadnicza ich ilość nie zostanie przez beneficjenta bazy odnaleziona); do grubych zaliczę jeszcze np. pomylenie płci (spotkałem się z Tomaszem zamiast Teresy) czy błędną interpretacje imienia (bowiem większość indeksujących wpisuje współczesny polski wariant imienia, niektóre niepospolite imiona zdecydowanie zaskakują sporo indeksujących, w konsekwencji powstają potworki lub przypisywane są podobnie brzmiące, niektórzy też nie radzą sobie z odmianą nazwisk przez przypadki i przez osoby panna/mężatka zwłaszcza w łacinie, również dawnych ludowych wariantach polszczyzny. Z drobnych błędów które niekoniecznie są winą indeksującego,wymienić należy, wszelkie przeinaczenia nazwisk, jak multi wariantowość w obrębie parafii, skrybowie spisywali ze słuchu, ponadto były okresy pisania \'y\' zamiast \'i\' czy \'j\', w pewnych obszarach płynnie spotykamy się z \'ty\' zamiast \'ci\'  ina opak, często występuje oboczność przy sufiksach \'owski\' = \'oski\' = \'ocki\', też wpływ Węgierki pisanie \'ss\' zamiast \'s\' (tu zdarza się że ligaturę drugiego \'s\', indeksujący traktują czasem jako \'ł\' czasem), jak i \'ś\' jako \'sz\', tudzież \'ą\' jako \'om\' i \'on\', jak i oboczność sufiksu \'wicz\' do \'wic\', \'ć\' do \'cz\', tak jak szereg podobnych,pojawiających się zapisów wpływających na konieczność wyszukiwania wielu wariantów danego nazwiska. Dodatkowo utrudnia nierzadko beznadziejny charakter pisma,który jest zbyt ozdobny, zbyt niechlujny, tudzież zdegradowanych np.wilgocią przez stulecia/dekady złego archiwizowania.';
  p_2_a = 'Serwis \'Geneteka\' działa względnie sprawnie, jednakże przy głębszych badaniach uciążliwe są ukryte informacje pod symbolami literki \'i\',aby je poznać każdorazowo trzeba najechać na ikonę,nie można ich ani zaznaczyć ani też skopiować, jak i wyszukać..; Niemożliwym jest też bardziej złożone filtrowanie czy  sortowanie, takie jakie znamy chociażby z Google-Sheet/MS-Excell.       Aby temu zaradzić, powstał mój skrypt, Który niestety nie jest  trywialny, pewnie niejeden z was rzeknie  iż jest to zbyt skomplikowane lub wymaga zbyt wielkiego nakładu czasu, jednakże mnie niezwykle ułatwiło,  oszczędzając na analizy mnóstwo czasu.';
  p_2_b = '';  

  constructor() { }

  ngOnInit(): void { }

}